title: Jay Barra's Page
email: jay.f.barra@gmail.com
description: >-
  I write software, design systems, fix bugs, and deploy great things.
baseurl: "" 
url: "https://draconic-systems.com"
github_username:  jaybarra

# Build settings
theme: minima
minima:
  skin: solarized-dark
plugins:
  - jekyll-feed
